name: Nightly

on:
  schedule:
    - cron: '0 0 * * * '

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: swiftlang/swift:nightly
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v
